### ISSUE TITLE
Fix: Coaching page missing intro text.

### ISSUE THREAD

**Issue by jamesMAwalker** [JamesMAWalker/eli-2022#1]
> Still some issues with the Coaching page. Right now "Intro Text" is not showing up ( Embody new ways of being through holistic coaching that transforms how you live and lead.). Where is this content suppose to be showing up? I put it in "The ELI Approach"  section. I will need to add more content there.  Let me know if that line, in the parentheses above, is suppose to be showing up somewhere different.

- Likely something to do with the markdown component.

**Comment by jamesMAwalker** [comment]
Issue with QuoteBlock component not receiving all needed props from Contentful.

**Comment by abrzench** [comment]
Thanks, I do see this change:)

**Comment by abrzench** [comment]
I realized I like it better with out this section. Can you please delete it?

**Comment by jamesMAwalker** [comment]
Will do! @abrzench
