### ISSUE TITLE
Fix: Headings not editable in offerings directory

### ISSUE THREAD

**Issue by jamesMAwalker** [JamesMAWalker/eli-2022#2]
> Offerings Page - I still can't edit the headings in the box. Where it says "Who's it For." Can you create a way for me to edit that? I want to change it to something like "Opportuntites for Growth." But, I would like to have the ability to change that if possible.

**Comment by jamesMAwalker** [comment]
These fields are now editable! They have also been updated to say "Opportunities for Growth".

**Comment by abrzench** [comment]
Thanks James, unfortunately, this is still not showing up on my end. Although the correct text is in contentful.

**Comment by jamesMAwalker** [comment]
Ah, apologies - looks like I never got the changes up to the public version of the site. Looks like it's live now!

@abrzench
