### ISSUE TITLE
Add: Markdown fields in coaching ethos

### ISSUE THREAD

**Issue by jamesMAwalker** [JamesMAWalker/eli-2022#3]
> The "Coaching Ethos" section needs rich formatting like "The ELI Approach" section.

**Comment by jamesMAwalker** [comment]
The issue was not that these fields were not added as rich text - it was that Contentful requires an **explicit line break.** To add an explicit line break while using the Contentful editor, hold `shift` and then press `enter`.

**Comment by abrzench** [comment]
Got it to work, thanks!
